config/routes.rb
Rails.application.routes.draw do
  get 'salesoffices/index'
  get 'salesoffices/edit'
  resources :equipment
  resources :salesoffices, except: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :salesoffices, dependent: :destroy
end

app/models/salesoffice.rb
class Salesoffice < ApplicationRecord
    belongs_to :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_params
      params.require(:equipment).permit(:equipmentcode, :dateBuyEquipment, :price, :rental, :maintenance, :salesoffice_id)
    end
end

app/controllers/salesoffices_controller.rb
class SalesofficesController < ApplicationController
  before_action :set_salesoffice, only: [:edit, :update, :destroy]
  
  def index
    @salesoffice = Salesoffice.new
    @salesoffices = Salesoffice.all
  end

  def create
    @salesoffice = Salesoffice.new(salesoffice_params)
    if @salesoffice.save
      redirect_to salesoffices_path
    else
      @salesoffices = Salesoffice.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @salesoffice.update(salesoffice_params)
      redirect_to salesoffices_path
    else
      render 'edit'
    end
  end

  def destroy
    @salesoffice.destroy
    redirect_to salesoffices_path
  end

  private

    def set_salesoffice
      @salesoffice = Salesoffice.find(params[:id])
    end

    def salesoffice_params
      params.require(:salesoffice).permit(:name)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/salesoffices_helper.rb
module SalesofficesHelper
end

app/views/equipment/_form.html.erb
<%= form_with(model: equipment, local: true) do |form| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
        <% equipment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :equipmentcode %>
    <%= form.text_field :equipmentcode %>
  </div>

  <div class="field">
    <%= form.label :dateBuyEquipment %>
    <%= form.date_select :dateBuyEquipment %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :rental %>
    <%= form.check_box :rental %>
  </div>

  <div class="field">
    <%= form.label :maintenance %>
    <%= form.check_box :maintenance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment</h1>

<table>
  <thead>
    <tr>
      <th>Equipmentcode</th>
      <th>Datebuyequipment</th>
      <th>Price</th>
      <th>Rental</th>
      <th>Maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= equipment.equipmentcode %></td>
        <td><%= equipment.dateBuyEquipment %></td>
        <td><%= equipment.price %></td>
        <td><%= equipment.rental %></td>
        <td><%= equipment.maintenance %></td>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equipment-code:</strong>
  <%= @equipment.equipmentcode %>
</p>

<p>
  <strong>Datebuyequipment:</strong>
  <%= @equipment.dateBuyEquipment %>
</p>

<p>
  <strong>Price:</strong>
  <%= @equipment.price %>
</p>

<p>
  <strong>Rental:</strong>
  <%= @equipment.rental %>
</p>

<p>
  <strong>Maintenance:</strong>
  <%= @equipment.maintenance %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManegingEquipment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/salesoffices/edit.html.erb
<h1>Salesoffices#edit</h1>
<p>Find me in app/views/salesoffices/edit.html.erb</p>

app/views/salesoffices/index.html.erb
<h1>Salesoffices#index</h1>
<p>Find me in app/views/salesoffices/index.html.erb</p>